# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.3.7
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: Travis
dependency_installation_mode: OCA
generate_requirements_txt: true
include_wkhtmltopdf: false
odoo_version: 14.0
rebel_module_groups: []
repo_description: Miscellaneous Odoo addons by Trevi that do not belong elsewhere.
repo_name: Miscellaneous Trevi Addons
repo_slug: trevi-misc
travis_apt_packages: []
travis_apt_sources: []
